### ISSUE TITLE
Bounty Program: Build an Airdrop Honoring System with StreamingFast (on any of the network supported by StreamingFast)

### ISSUE THREAD

**Issue by anthonyzzy** [streamingfast/streamingfast-client#1]
Problem: Any airdrop that is based around anything other than just "which address held a token in their wallet at blockheight X" often leads to confusion and missed addresses.

Bounty Details:

* Build an Airdrop Honoring System. 
* Select a project that **could** be doing an airdrop soon.
* Stream data from StreamingFast, analyse it to create a list of addresses that should be honored in the airdrop, along with a distribution algorithm. 
* Best algo wins!

**Comment by WillanLan** [comment]
good project!

**Comment by DeFi-xxx** [comment]
We are team DeFiPlus,we will try to do the project on Beijing Hackathon

**Comment by anthonyzzy** [comment]
> We are team DeFiPlus,we will try to do the project on Beijing Hackathon

Had a good chat with your team member at the Hackathon. Have fun, can't wait to see your submission.

**Comment by eka12** [comment]
How airdrop?

**Comment by anthonyzzy** [comment]
> How airdrop?

Not sure what you mean, Could you describe your question in more detail?

**Comment by lvmin216** [comment]
i think you can change the net,deal it in bsc or heco,not only the fee is low,but alao it's fast.from your question,i think it may teh net  is too crowded,

**Comment by lvmin216** [comment]
beacause i not see the code , i did not  know more，if you want more，please connect wth me。

**Comment by eka12** [comment]
@How airdrop

**Comment by anthonyzzy** [comment]
> @how airdrop

If you are asking what the airdrop rule should be used here, you can maybe refer to MASK's issuance rules: https://trusple.network/2021021811450.html, or something less complicated, but it should be more than just "which address held a token in their wallet at blockheight X".

**Comment by anthonyzzy** [comment]
> i think you can change the net,deal it in bsc or heco,not only the fee is low,but alao it's fast.from your question,i think it may teh net is too crowded,

That's a good point, StreamingFast actually supports BSC as well. What do you think @abourget?

**Comment by linruigongzi** [comment]
@anthonyzzy

**Comment by linruigongzi** [comment]
@anthonyzzy A basic implementation of Airdrop Honoring System like UNI all historical users can be claimed at a specific block range.

https://github.com/linruigongzi/StreamingFastAirdrop

can also have more strategies based on this project:

1. sort the historical users by token balance DESC to meet a limited airdrop or a distribution based on weight
2. sort the historical users by participate times DESC to meet a limited airdrop or distribution based on weight
3. Use more complex distribution algorithm as Streamingfast can get the data we want

**Comment by anthonyzzy** [comment]
> @anthonyzzy A basic implementation of Airdrop Honoring System like UNI all historical users can be claimed at a specific block range.
> 
> https://github.com/linruigongzi/StreamingFastAirdrop
> 
> can also have more strategies based on this project:
> 
> 1. sort the historical users by token balance DESC to meet a limited airdrop or a distribution based on weight
> 2. sort the historical users by participate times DESC to meet a limited airdrop or distribution based on weight
> 3. Use more complex distribution algorithm as Streamingfast can get the data we want

w00t, our first submission! @abourget, take a look.

**Comment by anthonyzzy** [comment]
We are still accepting more submissions. We've extended the bounty to this Saturday 3/28/2021, 12:44:50 PM. Remember, best algorithm wins!

**Comment by anthonyzzy** [comment]
Bounty issued to @linruigongzi's submission, congrats

https://github.com/streamingfast/streamingfast-client/issues/1#issuecomment-803503666
